from __future__ import annotations

MODE_NORMAL = "NORMAL"
MODE_COMMAND = "COMMAND"
MODE_SEARCH = "SEARCH"
MODE_CONFIRM = "CONFIRM"

MODE_HOME_SECTION_SELECT = "HOME_SECTION_SELECT"
MODE_HOME_REQUEST_SELECT = "HOME_REQUEST_SELECT"
MODE_HOME_REQUEST_EDIT = "HOME_REQUEST_EDIT"
MODE_HOME_REQUEST_METHOD_EDIT = "HOME_REQUEST_METHOD_EDIT"
MODE_HOME_AUTH_SELECT = "HOME_AUTH_SELECT"
MODE_HOME_AUTH_EDIT = "HOME_AUTH_EDIT"
MODE_HOME_AUTH_TYPE_EDIT = "HOME_AUTH_TYPE_EDIT"
MODE_HOME_AUTH_LOCATION_EDIT = "HOME_AUTH_LOCATION_EDIT"
MODE_HOME_PARAMS_SELECT = "HOME_PARAMS_SELECT"
MODE_HOME_PARAMS_EDIT = "HOME_PARAMS_EDIT"
MODE_HOME_HEADERS_SELECT = "HOME_HEADERS_SELECT"
MODE_HOME_HEADERS_EDIT = "HOME_HEADERS_EDIT"
MODE_HOME_BODY_SELECT = "HOME_BODY_SELECT"
MODE_HOME_BODY_TYPE_EDIT = "HOME_BODY_TYPE_EDIT"
MODE_HOME_BODY_RAW_TYPE_EDIT = "HOME_BODY_RAW_TYPE_EDIT"
MODE_HOME_BODY_EDIT = "HOME_BODY_EDIT"
MODE_HOME_BODY_TEXTAREA = "HOME_BODY_TEXTAREA"
MODE_HOME_RESPONSE_SELECT = "HOME_RESPONSE_SELECT"
MODE_HOME_RESPONSE_TEXTAREA = "HOME_RESPONSE_TEXTAREA"

MODE_ENV_SELECT = "ENV_SELECT"
MODE_ENV_EDIT = "ENV_EDIT"

MODE_HISTORY_RESPONSE_SELECT = "HISTORY_RESPONSE_SELECT"
MODE_HISTORY_RESPONSE_TEXTAREA = "HISTORY_RESPONSE_TEXTAREA"

HOME_MODES = frozenset(
    {
        MODE_HOME_SECTION_SELECT,
        MODE_HOME_REQUEST_SELECT,
        MODE_HOME_REQUEST_EDIT,
        MODE_HOME_REQUEST_METHOD_EDIT,
        MODE_HOME_AUTH_SELECT,
        MODE_HOME_AUTH_EDIT,
        MODE_HOME_AUTH_TYPE_EDIT,
        MODE_HOME_AUTH_LOCATION_EDIT,
        MODE_HOME_PARAMS_SELECT,
        MODE_HOME_PARAMS_EDIT,
        MODE_HOME_HEADERS_SELECT,
        MODE_HOME_HEADERS_EDIT,
        MODE_HOME_BODY_SELECT,
        MODE_HOME_BODY_TYPE_EDIT,
        MODE_HOME_BODY_RAW_TYPE_EDIT,
        MODE_HOME_BODY_EDIT,
        MODE_HOME_BODY_TEXTAREA,
        MODE_HOME_RESPONSE_SELECT,
        MODE_HOME_RESPONSE_TEXTAREA,
    }
)

REQUEST_RESPONSE_SHORTCUT_MODES = frozenset(
    {
        MODE_HOME_SECTION_SELECT,
        MODE_HOME_REQUEST_SELECT,
        MODE_HOME_REQUEST_METHOD_EDIT,
        MODE_HOME_AUTH_SELECT,
        MODE_HOME_AUTH_TYPE_EDIT,
        MODE_HOME_AUTH_LOCATION_EDIT,
        MODE_HOME_PARAMS_SELECT,
        MODE_HOME_HEADERS_SELECT,
        MODE_HOME_BODY_SELECT,
        MODE_HOME_BODY_TYPE_EDIT,
        MODE_HOME_BODY_RAW_TYPE_EDIT,
    }
)

COMMAND_BLOCKED_MODES = frozenset(
    {
        MODE_CONFIRM,
        MODE_COMMAND,
        MODE_SEARCH,
        MODE_HOME_REQUEST_EDIT,
        MODE_HOME_REQUEST_METHOD_EDIT,
        MODE_HOME_AUTH_EDIT,
        MODE_HOME_AUTH_TYPE_EDIT,
        MODE_HOME_AUTH_LOCATION_EDIT,
        MODE_HOME_PARAMS_EDIT,
        MODE_HOME_HEADERS_EDIT,
        MODE_HOME_BODY_TYPE_EDIT,
        MODE_HOME_BODY_RAW_TYPE_EDIT,
        MODE_HOME_BODY_EDIT,
        MODE_HOME_BODY_TEXTAREA,
        MODE_HOME_RESPONSE_TEXTAREA,
        MODE_HISTORY_RESPONSE_TEXTAREA,
        MODE_ENV_EDIT,
    }
)

INLINE_EDIT_MODES = frozenset(
    {
        MODE_HOME_REQUEST_EDIT,
        MODE_HOME_AUTH_EDIT,
        MODE_HOME_PARAMS_EDIT,
        MODE_HOME_HEADERS_EDIT,
        MODE_HOME_BODY_EDIT,
        MODE_ENV_EDIT,
    }
)

TEXTAREA_MODES = frozenset(
    {
        MODE_HOME_BODY_TEXTAREA,
        MODE_HOME_RESPONSE_TEXTAREA,
        MODE_HISTORY_RESPONSE_TEXTAREA,
    }
)


def display_mode(mode: str) -> str:
    if mode.endswith("_SELECT"):
        return "SELECT"
    if mode.endswith("_EDIT"):
        return "EDIT"
    return mode
